// <auto-generated />
using CasaDoCodigo.Areas.Catalogo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CasaDoCodigo.Areas.Catalogo.Data.Migrations
{
    [DbContext(typeof(CatalogoDbContext))]
    [Migration("20190904185019_AreaCatalogo")]
    partial class AreaCatalogo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CasaDoCodigo.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Livros de Programação / Lógica"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Livros de Programação / Java"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Livros de Programação / .NET"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Livros de Programação / PHP"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Livros de Programação / Games"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Livros de Programação / Funcional"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Livros de Programação / Outros"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Livros de Mobile / IOS"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Livros de Mobile / Android"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Livros de Mobile / Multiplataforma"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Livros de Mobile / Outros"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Livros de Front-end / HTML e CSS"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Livros de Front-end / JavaScript"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Livros de Front-end / Outros"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Livros de Infraestrutura / Redes"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Livros de Infraestrutura / Dados"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Livros de Infraestrutura / Outros"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Livros de Business / Startups"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Livros de Business / Marketing Digital"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Livros de Business / Gestão"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Livros de Business / Agile"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Livros de Business / Outros"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Livros de Design e UX / Geral"
                        });
                });

            modelBuilder.Entity("CasaDoCodigo.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaId");

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Codigo = "001",
                            Nome = "Lógica de Programação: Crie seus primeiros programas usando Javascript e HTML",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Codigo = "002",
                            Nome = "Introdução à Computação: Da Lógica aos jogos com Ruby",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Codigo = "003",
                            Nome = "Scratch: Um jeito divertido de aprender programação",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Codigo = "004",
                            Nome = "Introdução à programação em C: Os primeiros passos de um desenvolvedor",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Codigo = "005",
                            Nome = "App Inventor: Seus primeiros aplicativos Android",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 1,
                            Codigo = "006",
                            Nome = "Construct 2: Crie o seu primeiro jogo multiplataforma",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            Codigo = "007",
                            Nome = "Aplicações Java para a web com JSF e JPA",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Codigo = "008",
                            Nome = "Java SE 8 Programmer I: O guia para sua certificação Oracle Certified Associate",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            Codigo = "009",
                            Nome = "SOA aplicado: Integrando com web services e além",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            Codigo = "010",
                            Nome = "Design Patterns com Java: Projeto orientado a objetos guiado por padrões",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 2,
                            Codigo = "011",
                            Nome = "Spring MVC: Domine o principal framework web Java",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 2,
                            Codigo = "012",
                            Nome = "Vire o jogo com Spring Framework",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 2,
                            Codigo = "013",
                            Nome = "Orientação a Objetos e SOLID para Ninjas: Projetando classes flexíveis",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 2,
                            Codigo = "014",
                            Nome = "Test-Driven Development: Teste e Design no Mundo Real",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 2,
                            Codigo = "015",
                            Nome = "Introdução à Arquitetura e Design de Software: Uma visão sobre a plataforma Java",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 2,
                            Codigo = "016",
                            Nome = "Desbravando Java e Orientação a Objetos: Um guia para o iniciante da linguagem",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 2,
                            Codigo = "017",
                            Nome = "Java 8 Prático: Lambdas, Streams e os novos recursos da linguagem",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 2,
                            Codigo = "018",
                            Nome = "JSF Eficaz: As melhores práticas para o desenvolvedor web Java",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 2,
                            Codigo = "019",
                            Nome = "Testes automatizados de software: Um guia prático",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 2,
                            Codigo = "020",
                            Nome = "Java EE: Aproveite toda a plataforma para construir aplicações",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 21,
                            CategoriaId = 2,
                            Codigo = "021",
                            Nome = "JPA Eficaz: As melhores práticas de persistência de dados em Java",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 22,
                            CategoriaId = 2,
                            Codigo = "022",
                            Nome = "CDI: Integre as dependências e contextos do seu código Java",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 23,
                            CategoriaId = 2,
                            Codigo = "023",
                            Nome = "JavaFX: Interfaces com qualidade para aplicações desktop",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 24,
                            CategoriaId = 2,
                            Codigo = "024",
                            Nome = "VRaptor: Desenvolvimento ágil para web com Java",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 25,
                            CategoriaId = 2,
                            Codigo = "025",
                            Nome = "Spring Boot: Acelere o desenvolvimento de microsserviços",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 26,
                            CategoriaId = 2,
                            Codigo = "026",
                            Nome = "Orientação a Objetos: Aprenda seus conceitos e suas aplicabilidades de forma efetiva",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 27,
                            CategoriaId = 2,
                            Codigo = "027",
                            Nome = "Componentes Reutilizáveis em Java com Reflexão e Anotações",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 28,
                            CategoriaId = 2,
                            Codigo = "028",
                            Nome = "Segurança em aplicações Web",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 29,
                            CategoriaId = 2,
                            Codigo = "029",
                            Nome = "Java 9: Interativo, reativo e modularizado",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 30,
                            CategoriaId = 2,
                            Codigo = "030",
                            Nome = "Explorando APIs e bibliotecas Java: JDBC, IO, Threads, JavaFX e mais",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 31,
                            CategoriaId = 2,
                            Codigo = "031",
                            Nome = "OAuth 2.0: Proteja suas aplicações com o Spring Security OAuth2",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 32,
                            CategoriaId = 2,
                            Codigo = "032",
                            Nome = "A lógica do jogo: Recriando clássicos da história dos videogames",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 33,
                            CategoriaId = 2,
                            Codigo = "033",
                            Nome = "Play Framework: Java para web sem Servlets e com diversão",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 34,
                            CategoriaId = 2,
                            Codigo = "034",
                            Nome = "iReport: Crie relatórios práticos e elegantes",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 35,
                            CategoriaId = 2,
                            Codigo = "035",
                            Nome = "Algoritmos em Java: Busca, ordenação e análise",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 36,
                            CategoriaId = 2,
                            Codigo = "036",
                            Nome = "MundoJ: Segurança com Java",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 37,
                            CategoriaId = 2,
                            Codigo = "037",
                            Nome = "Refatorando com padrões de projeto: Um guia em Java",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 38,
                            CategoriaId = 2,
                            Codigo = "038",
                            Nome = "DSL: Quebre a barreira entre desenvolvimento e negócios",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 39,
                            CategoriaId = 3,
                            Codigo = "039",
                            Nome = "Desenvolvimento web com ASP.NET MVC",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 40,
                            CategoriaId = 3,
                            Codigo = "040",
                            Nome = "Test-Driven Development: Teste e Design no Mundo Real com .NET",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 41,
                            CategoriaId = 3,
                            Codigo = "041",
                            Nome = "ASP.NET MVC5: Crie aplicações web na plataforma Microsoft®",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 42,
                            CategoriaId = 3,
                            Codigo = "042",
                            Nome = "Orientação a Objetos: Aprenda seus conceitos e suas aplicabilidades de forma efetiva",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 43,
                            CategoriaId = 3,
                            Codigo = "043",
                            Nome = "C# e Visual Studio: Desenvolvimento de aplicações desktop",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 44,
                            CategoriaId = 3,
                            Codigo = "044",
                            Nome = "Web Services REST com ASP .NET Web API e Windows Azure",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 45,
                            CategoriaId = 3,
                            Codigo = "045",
                            Nome = "ASP.NET Core MVC: Aplicações modernas em conjunto com o Entity Framework",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 46,
                            CategoriaId = 3,
                            Codigo = "046",
                            Nome = "Orientação a Objetos em C#: Conceitos e implementações em .NET",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 47,
                            CategoriaId = 3,
                            Codigo = "047",
                            Nome = "Programação funcional em .NET: Explore um novo universo",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 48,
                            CategoriaId = 4,
                            Codigo = "048",
                            Nome = "Desenvolvimento web com PHP e MySQL",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 49,
                            CategoriaId = 4,
                            Codigo = "049",
                            Nome = "PHP e Laravel: Crie aplicações web como um verdadeiro artesão",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 50,
                            CategoriaId = 4,
                            Codigo = "050",
                            Nome = "Zend Certified Engineer: Descomplicando a certificação PHP",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 51,
                            CategoriaId = 4,
                            Codigo = "051",
                            Nome = "CodeIgniter: Produtividade na criação de aplicações web em PHP",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 52,
                            CategoriaId = 4,
                            Codigo = "052",
                            Nome = "Test-Driven Development: Teste e Design no Mundo Real com PHP",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 53,
                            CategoriaId = 4,
                            Codigo = "053",
                            Nome = "Do PHP ao Zend Framework: Domine as boas práticas",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 54,
                            CategoriaId = 4,
                            Codigo = "054",
                            Nome = "Coleção CodeIgniter + Zend PHP",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 55,
                            CategoriaId = 5,
                            Codigo = "055",
                            Nome = "Introdução à Computação: Da Lógica aos jogos com Ruby",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 56,
                            CategoriaId = 5,
                            Codigo = "056",
                            Nome = "A lógica do jogo: Recriando clássicos da história dos videogames",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 57,
                            CategoriaId = 5,
                            Codigo = "057",
                            Nome = "Desenvolva jogos com HTML5 Canvas e JavaScript",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 58,
                            CategoriaId = 5,
                            Codigo = "058",
                            Nome = "Desenvolvimento de Jogos para Android: Explore sua imaginação com o framework Cocos2D",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 59,
                            CategoriaId = 5,
                            Codigo = "059",
                            Nome = "Desenvolvimento de Jogos para iOS: Explore sua imaginação com o framework Cocos2D",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 60,
                            CategoriaId = 5,
                            Codigo = "060",
                            Nome = "Jogos em HTML5: Explore o mobile e física",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 61,
                            CategoriaId = 5,
                            Codigo = "061",
                            Nome = "Jogos Android: Crie um game do zero usando classes nativas",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 62,
                            CategoriaId = 5,
                            Codigo = "062",
                            Nome = "Lean Game Development: Desenvolvimento enxuto de jogos",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 63,
                            CategoriaId = 5,
                            Codigo = "063",
                            Nome = "Construct 2: Crie o seu primeiro jogo multiplataforma",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 64,
                            CategoriaId = 6,
                            Codigo = "064",
                            Nome = "Scala: Como escalar sua produtividade",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 65,
                            CategoriaId = 6,
                            Codigo = "065",
                            Nome = "Elixir: Do zero à concorrência",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 66,
                            CategoriaId = 6,
                            Codigo = "066",
                            Nome = "Haskell: Uma introdução à programação funcional",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 67,
                            CategoriaId = 6,
                            Codigo = "067",
                            Nome = "OCaml: Programação funcional na prática",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 68,
                            CategoriaId = 6,
                            Codigo = "068",
                            Nome = "Programação funcional em .NET: Explore um novo universo",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 69,
                            CategoriaId = 6,
                            Codigo = "069",
                            Nome = "Programação Funcional e Concorrente em Rust",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 70,
                            CategoriaId = 7,
                            Codigo = "070",
                            Nome = "Aplicações web real-time com Node.js",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 71,
                            CategoriaId = 7,
                            Codigo = "071",
                            Nome = "REST: Construa API's inteligentes de maneira simples",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 72,
                            CategoriaId = 7,
                            Codigo = "072",
                            Nome = "Ruby on Rails: coloque sua aplicação web nos trilhos",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 73,
                            CategoriaId = 7,
                            Codigo = "073",
                            Nome = "Mean: Full stack JavaScript para aplicações web com MongoDB, Express, Angular e Node",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 74,
                            CategoriaId = 7,
                            Codigo = "074",
                            Nome = "Swift: Programe para iPhone e iPad",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 75,
                            CategoriaId = 7,
                            Codigo = "075",
                            Nome = "Python: Escreva seus primeiros programas",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 76,
                            CategoriaId = 7,
                            Codigo = "076",
                            Nome = "Ruby: Aprenda a programar na linguagem mais divertida",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 77,
                            CategoriaId = 7,
                            Codigo = "077",
                            Nome = "Construindo APIs REST com Node.js",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 78,
                            CategoriaId = 7,
                            Codigo = "078",
                            Nome = "Programando em Go: Crie aplicações com a linguagem do Google",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 79,
                            CategoriaId = 7,
                            Codigo = "079",
                            Nome = "OAuth 2.0: Proteja suas aplicações com o Spring Security OAuth2",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 80,
                            CategoriaId = 7,
                            Codigo = "080",
                            Nome = "Meteor: Criando aplicações web real-time com JavaScript",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 81,
                            CategoriaId = 7,
                            Codigo = "081",
                            Nome = "Cucumber e RSpec: Construa aplicações Ruby com testes e especificações",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 82,
                            CategoriaId = 7,
                            Codigo = "082",
                            Nome = "Falando de Grails: Altíssima produtividade no desenvolvimento web",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 83,
                            CategoriaId = 7,
                            Codigo = "083",
                            Nome = "Guia do mestre programador: pensando como pirata, evoluindo como jedi",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 84,
                            CategoriaId = 7,
                            Codigo = "084",
                            Nome = "Thoughtworks Antologia Brasil: Histórias de aprendizado e inovação",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 85,
                            CategoriaId = 7,
                            Codigo = "085",
                            Nome = "Introdução à programação em C: Os primeiros passos de um desenvolvedor",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 86,
                            CategoriaId = 7,
                            Codigo = "086",
                            Nome = "Test Driven Development: Teste e design no mundo real com Ruby",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 87,
                            CategoriaId = 7,
                            Codigo = "087",
                            Nome = "Fragmentos de um programador: Artigos e insights da carreira de um profissional",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 88,
                            CategoriaId = 7,
                            Codigo = "088",
                            Nome = "Desenvolvimento efetivo na plataforma Microsoft: Como desenvolver e suportar software que funciona",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 89,
                            CategoriaId = 7,
                            Codigo = "089",
                            Nome = "Primeiros passos com Node.js",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 90,
                            CategoriaId = 7,
                            Codigo = "090",
                            Nome = "RSpec: Crie especificações executáveis em Ruby",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 91,
                            CategoriaId = 7,
                            Codigo = "091",
                            Nome = "ABAP: O guia de sobrevivência do profissional moderno",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 92,
                            CategoriaId = 7,
                            Codigo = "092",
                            Nome = "Refatorando com padrões de projeto: Um guia em Ruby",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 93,
                            CategoriaId = 7,
                            Codigo = "093",
                            Nome = "Microsoft Kinect: Crie aplicações interativas",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 94,
                            CategoriaId = 7,
                            Codigo = "094",
                            Nome = "Canivete suíço do desenvolvedor Node",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 95,
                            CategoriaId = 7,
                            Codigo = "095",
                            Nome = "DSL: Quebre a barreira entre desenvolvimento e negócios",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 96,
                            CategoriaId = 7,
                            Codigo = "096",
                            Nome = "Octave: Seus primeiros passos na programação científica",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 97,
                            CategoriaId = 7,
                            Codigo = "097",
                            Nome = "Rust: Concorrência e alta performance com segurança",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 98,
                            CategoriaId = 7,
                            Codigo = "098",
                            Nome = "Programação Funcional e Concorrente em Rust",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 99,
                            CategoriaId = 8,
                            Codigo = "099",
                            Nome = "Swift: Programe para iPhone e iPad",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 100,
                            CategoriaId = 8,
                            Codigo = "100",
                            Nome = "iOS: Programe para iPhone e iPad",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 101,
                            CategoriaId = 8,
                            Codigo = "101",
                            Nome = "Desenvolvimento de Jogos para iOS: Explore sua imaginação com o framework Cocos2D",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 102,
                            CategoriaId = 9,
                            Codigo = "102",
                            Nome = "Google Android: crie aplicações para celulares e tablets",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 103,
                            CategoriaId = 9,
                            Codigo = "103",
                            Nome = "Desenvolvimento de Jogos para Android: Explore sua imaginação com o framework Cocos2D",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 104,
                            CategoriaId = 9,
                            Codigo = "104",
                            Nome = "Jogos Android: Crie um game do zero usando classes nativas",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 105,
                            CategoriaId = 9,
                            Codigo = "105",
                            Nome = "Entrega contínua em Android: Como automatizar a distribuição de apps",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 106,
                            CategoriaId = 9,
                            Codigo = "106",
                            Nome = "App Inventor: Seus primeiros aplicativos Android",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 107,
                            CategoriaId = 10,
                            Codigo = "107",
                            Nome = "Aplicações mobile híbridas com Cordova e PhoneGap",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 108,
                            CategoriaId = 10,
                            Codigo = "108",
                            Nome = "Xamarin Forms: Desenvolvimento de aplicações móveis multiplataforma",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 109,
                            CategoriaId = 10,
                            Codigo = "109",
                            Nome = "Ionic Framework: Construa aplicativos para todas as plataformas mobile",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 110,
                            CategoriaId = 10,
                            Codigo = "110",
                            Nome = "Cordova avançado e PhoneGap: Um guia detalhado do zero à publicação",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 111,
                            CategoriaId = 11,
                            Codigo = "111",
                            Nome = "Criando aplicações para o seu Windows Phone",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 112,
                            CategoriaId = 11,
                            Codigo = "112",
                            Nome = "Progressive Web Apps: Construa aplicações progressivas com React",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 113,
                            CategoriaId = 11,
                            Codigo = "113",
                            Nome = "Criando aplicações para o seu Windows Phone - Edição Windows Runtime",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 114,
                            CategoriaId = 12,
                            Codigo = "114",
                            Nome = "HTML5 e CSS3: Domine a web do futuro",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 115,
                            CategoriaId = 12,
                            Codigo = "115",
                            Nome = "Web Design Responsivo: Páginas adaptáveis para todos os dispositivos",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 116,
                            CategoriaId = 12,
                            Codigo = "116",
                            Nome = "A Web Mobile: Design Responsivo e além para uma Web adaptada ao mundo mobile",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 117,
                            CategoriaId = 12,
                            Codigo = "117",
                            Nome = "Desenvolva jogos com HTML5 Canvas e JavaScript",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 118,
                            CategoriaId = 12,
                            Codigo = "118",
                            Nome = "Coletânea Front-end: Uma antologia da comunidade front-end brasileira",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 119,
                            CategoriaId = 12,
                            Codigo = "119",
                            Nome = "CSS Eficiente: Técnicas e ferramentas que fazem a diferença nos seus estilos",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 120,
                            CategoriaId = 12,
                            Codigo = "120",
                            Nome = "Jogos em HTML5: Explore o mobile e física",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 121,
                            CategoriaId = 12,
                            Codigo = "121",
                            Nome = "Sass: Aprendendo pré-processadores CSS",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 122,
                            CategoriaId = 12,
                            Codigo = "122",
                            Nome = "Turbine seu CSS: Folhas de estilo inteligentes com Sass",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 123,
                            CategoriaId = 13,
                            Codigo = "123",
                            Nome = "Dominando JavaScript com jQuery",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 124,
                            CategoriaId = 13,
                            Codigo = "124",
                            Nome = "Mean: Full stack JavaScript para aplicações web com MongoDB, Express, Angular e Node",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 125,
                            CategoriaId = 13,
                            Codigo = "125",
                            Nome = "Crie aplicações com Angular: O novo framework do Google",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 126,
                            CategoriaId = 13,
                            Codigo = "126",
                            Nome = "Cangaceiro JavaScript: Uma aventura no sertão da programação",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 127,
                            CategoriaId = 13,
                            Codigo = "127",
                            Nome = "Desenvolva jogos com HTML5 Canvas e JavaScript",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 128,
                            CategoriaId = 13,
                            Codigo = "128",
                            Nome = "Coletânea Front-end: Uma antologia da comunidade front-end brasileira",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 129,
                            CategoriaId = 13,
                            Codigo = "129",
                            Nome = "ECMAScript 6: Entre de cabeça no futuro do JavaScript",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 130,
                            CategoriaId = 13,
                            Codigo = "130",
                            Nome = "Meteor: Criando aplicações web real-time com JavaScript",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 131,
                            CategoriaId = 13,
                            Codigo = "131",
                            Nome = "Vue.js: Construa aplicações incríveis",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 132,
                            CategoriaId = 13,
                            Codigo = "132",
                            Nome = "Front-end com Vue.js: Da teoria à prática sem complicações",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 133,
                            CategoriaId = 13,
                            Codigo = "133",
                            Nome = "Protractor: Lições sobre testes end-to-end automatizados",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 134,
                            CategoriaId = 13,
                            Codigo = "134",
                            Nome = "jQuery Mobile: Desenvolva interfaces para múltiplos dispositivos",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 135,
                            CategoriaId = 13,
                            Codigo = "135",
                            Nome = "Ember.js: Conheça o framework para aplicações web ambiciosas",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 136,
                            CategoriaId = 14,
                            Codigo = "136",
                            Nome = "Guia Front-End: O caminho das pedras para ser um dev Front-End",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 137,
                            CategoriaId = 14,
                            Codigo = "137",
                            Nome = "Introdução à Web Semântica: A inteligência da informação",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 138,
                            CategoriaId = 14,
                            Codigo = "138",
                            Nome = "Progressive Web Apps: Construa aplicações progressivas com React",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 139,
                            CategoriaId = 15,
                            Codigo = "139",
                            Nome = "Desconstruindo a Web: As tecnologias por trás de uma requisição",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 140,
                            CategoriaId = 16,
                            Codigo = "140",
                            Nome = "Desenvolvimento web com PHP e MySQL",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 141,
                            CategoriaId = 16,
                            Codigo = "141",
                            Nome = "MongoDB: Construa novas aplicações com novas tecnologias",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 142,
                            CategoriaId = 16,
                            Codigo = "142",
                            Nome = "Big Data: Técnicas e tecnologias para extração de valor dos dados",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 143,
                            CategoriaId = 16,
                            Codigo = "143",
                            Nome = "MySQL: Comece com o principal banco de dados open source do mercado",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 144,
                            CategoriaId = 16,
                            Codigo = "144",
                            Nome = "PL/SQL: Domine a linguagem do banco de dados Oracle",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 145,
                            CategoriaId = 16,
                            Codigo = "145",
                            Nome = "SQL: Uma abordagem para bancos de dados Oracle",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 146,
                            CategoriaId = 16,
                            Codigo = "146",
                            Nome = "Machine Learning: Introdução à classificação",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 147,
                            CategoriaId = 16,
                            Codigo = "147",
                            Nome = "Elasticsearch: Consumindo dados real-time com ELK",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 148,
                            CategoriaId = 16,
                            Codigo = "148",
                            Nome = "Business Intelligence: Implementar do jeito certo e a custo zero",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 149,
                            CategoriaId = 16,
                            Codigo = "149",
                            Nome = "NoSQL: Como armazenar os dados de uma aplicação moderna",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 150,
                            CategoriaId = 16,
                            Codigo = "150",
                            Nome = "Armazenando dados com Redis",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 151,
                            CategoriaId = 16,
                            Codigo = "151",
                            Nome = "PostgreSQL: Banco de dados para aplicações web modernas",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 152,
                            CategoriaId = 17,
                            Codigo = "152",
                            Nome = "Controlando versões com Git e GitHub",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 153,
                            CategoriaId = 17,
                            Codigo = "153",
                            Nome = "DevOps na prática: entrega de software confiável e automatizada",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 154,
                            CategoriaId = 17,
                            Codigo = "154",
                            Nome = "Containers com Docker: Do desenvolvimento à produção",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 155,
                            CategoriaId = 17,
                            Codigo = "155",
                            Nome = "Caixa de Ferramentas DevOps: Um guia para construção, administração e arquitetura de sistemas modernos",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 156,
                            CategoriaId = 17,
                            Codigo = "156",
                            Nome = "Jenkins: Automatize tudo sem complicações",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 157,
                            CategoriaId = 17,
                            Codigo = "157",
                            Nome = "Começando com o Linux: Comandos, serviços e administração",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 158,
                            CategoriaId = 17,
                            Codigo = "158",
                            Nome = "Segurança em aplicações Web",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 159,
                            CategoriaId = 17,
                            Codigo = "159",
                            Nome = "Thoughtworks Antologia Brasil: Histórias de aprendizado e inovação",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 160,
                            CategoriaId = 17,
                            Codigo = "160",
                            Nome = "Arduino: Guia para colocar suas ideias em prática",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 161,
                            CategoriaId = 17,
                            Codigo = "161",
                            Nome = "Arduino prático: 10 projetos para executar, aprender, modificar e dominar o mundo",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 162,
                            CategoriaId = 17,
                            Codigo = "162",
                            Nome = "Azure: Coloque suas plataformas e serviços no cloud",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 163,
                            CategoriaId = 17,
                            Codigo = "163",
                            Nome = "Desenvolvimento efetivo na plataforma Microsoft: Como desenvolver e suportar software que funciona",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 164,
                            CategoriaId = 17,
                            Codigo = "164",
                            Nome = "Google App Engine: Construindo serviços na nuvem",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 165,
                            CategoriaId = 17,
                            Codigo = "165",
                            Nome = "Entrega contínua em Android: Como automatizar a distribuição de apps",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 166,
                            CategoriaId = 17,
                            Codigo = "166",
                            Nome = "Windows Server 2012 R2: Estudo dirigido para MCSA prova 70-410",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 167,
                            CategoriaId = 18,
                            Codigo = "167",
                            Nome = "Guia da Startup: Como startups e empresas estabelecidas podem criar produtos de software rentáveis",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 168,
                            CategoriaId = 18,
                            Codigo = "168",
                            Nome = "Direto ao Ponto: Criando produtos de forma enxuta",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 169,
                            CategoriaId = 18,
                            Codigo = "169",
                            Nome = "Thoughtworks Antologia Brasil: Histórias de aprendizado e inovação",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 170,
                            CategoriaId = 18,
                            Codigo = "170",
                            Nome = "Economia do acesso: e os modelos de negócios baseados em compartilhamento, recorrência e assinatura",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 171,
                            CategoriaId = 18,
                            Codigo = "171",
                            Nome = "A jornada do empreendedor: O herói da nossa Era",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 172,
                            CategoriaId = 18,
                            Codigo = "172",
                            Nome = "Making it right: Gestão de produtos no mundo das startups",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 173,
                            CategoriaId = 19,
                            Codigo = "173",
                            Nome = "SEO Prático: Seu site na primeira página das buscas",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 174,
                            CategoriaId = 19,
                            Codigo = "174",
                            Nome = "Marketing de conteúdo: Estratégias para entregar o que seu público quer consumir",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 175,
                            CategoriaId = 20,
                            Codigo = "175",
                            Nome = "Gestão de produtos de software: Como aumentar as chances de sucesso do seu software",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 176,
                            CategoriaId = 20,
                            Codigo = "176",
                            Nome = "Métricas Ágeis: Obtenha melhores resultados em sua equipe",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 177,
                            CategoriaId = 20,
                            Codigo = "177",
                            Nome = "Lean Enterprise: Como empresas de alta performance inovam em escala",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 178,
                            CategoriaId = 20,
                            Codigo = "178",
                            Nome = "A jornada do empreendedor: O herói da nossa Era",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 179,
                            CategoriaId = 20,
                            Codigo = "179",
                            Nome = "Making it right: Gestão de produtos no mundo das startups",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 180,
                            CategoriaId = 21,
                            Codigo = "180",
                            Nome = "Scrum: Gestão ágil para projetos de sucesso",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 181,
                            CategoriaId = 21,
                            Codigo = "181",
                            Nome = "Agile: Desenvolvimento de software com entregas frequentes e foco no valor de negócio",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 182,
                            CategoriaId = 21,
                            Codigo = "182",
                            Nome = "Métricas Ágeis: Obtenha melhores resultados em sua equipe",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 183,
                            CategoriaId = 21,
                            Codigo = "183",
                            Nome = "eXtreme Programming: Práticas para o dia a dia no desenvolvimento ágil de software",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 184,
                            CategoriaId = 21,
                            Codigo = "184",
                            Nome = "Scrum 360: Um guia completo e prático de agilidade",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 185,
                            CategoriaId = 22,
                            Codigo = "185",
                            Nome = "O Programador Apaixonado: Construindo uma carreira notável em desenvolvimento de software",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 186,
                            CategoriaId = 22,
                            Codigo = "186",
                            Nome = "O Mantra da Produtividade: Aprimore sua produtividade com técnicas de foco e organização pessoal",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 187,
                            CategoriaId = 22,
                            Codigo = "187",
                            Nome = "Learning 3.0: Como os profissionais criativos aprendem",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 188,
                            CategoriaId = 22,
                            Codigo = "188",
                            Nome = "Lean Game Development: Desenvolvimento enxuto de jogos",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 189,
                            CategoriaId = 23,
                            Codigo = "189",
                            Nome = "Introdução e boas práticas em UX Design",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 190,
                            CategoriaId = 23,
                            Codigo = "190",
                            Nome = "Conhecendo o Adobe Photoshop CS6",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 191,
                            CategoriaId = 23,
                            Codigo = "191",
                            Nome = "Edição e organização de fotos com Adobe Lightroom",
                            Preco = 49.90m
                        },
                        new
                        {
                            Id = 192,
                            CategoriaId = 23,
                            Codigo = "192",
                            Nome = "Vale presente Casa do Código",
                            Preco = 49.90m
                        });
                });

            modelBuilder.Entity("CasaDoCodigo.Models.Produto", b =>
                {
                    b.HasOne("CasaDoCodigo.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
